# Generated by Django 6.0.3 on 2026-03-08 00:34

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_homepage_hero_about_cta_homepage_hero_about_cta_link_and_more'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
            ],
            options={
                'verbose_name_plural': 'Values',
            },
        ),
        migrations.CreateModel(
            name='StatCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Counters',
            },
        ),
        migrations.CreateModel(
            name='TermsPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('date', models.DateField(verbose_name='Last updated')),
                ('body', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='About',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('hero_title', models.CharField(blank=True, help_text='Write an introduction for the page', max_length=255)),
                ('hero_description', models.TextField(blank=True, help_text='Write an introduction for the about page', max_length=500)),
                ('mission_body', wagtail.fields.RichTextField(blank=True)),
                ('lead_name', models.CharField(blank=True, help_text="Write the Lead's name", max_length=255)),
                ('lead_role', models.CharField(blank=True, help_text="Write the Lead's role", max_length=255)),
                ('values_title', models.CharField(blank=True, help_text='Our values', max_length=255)),
                ('values_description', models.TextField(blank=True, help_text='Write an description', max_length=500)),
                ('presence_body', wagtail.fields.RichTextField(blank=True)),
                ('image', models.ForeignKey(blank=True, help_text='About image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('lead_image', models.ForeignKey(blank=True, help_text='Lead profile', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('values', modelcluster.fields.ParentalManyToManyField(blank=True, to='home.communityvalue')),
                ('counters', modelcluster.fields.ParentalManyToManyField(blank=True, to='home.statcounter')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
