# Generated by Django 6.0.3 on 2026-03-07 23:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='hero_about_cta',
            field=models.CharField(blank=True, help_text='Text to display on About button', max_length=255, verbose_name='About CTA'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_about_cta_link',
            field=models.ForeignKey(blank=True, help_text='Choose a page to link to for the About to Action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='About link'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_description',
            field=models.TextField(blank=True, help_text='Write an introduction for the site', max_length=500),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_title',
            field=models.CharField(blank=True, help_text='Write an introduction for the site', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='image',
            field=models.ForeignKey(blank=True, help_text='Homepage image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
