# Generated by Django 6.0.3 on 2026-03-08 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NavigationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn URL')),
                ('github_url', models.URLField(blank=True, verbose_name='GitHub URL')),
                ('whatsapp_url', models.URLField(blank=True, verbose_name='WhatsApp URL')),
                ('tiktok_url', models.URLField(blank=True, verbose_name='Tiktok URL')),
                ('facebook_url', models.URLField(blank=True, verbose_name='Facebook URL')),
                ('x_url', models.URLField(blank=True, verbose_name='X URL')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
