# Generated by Django 6.0.3 on 2026-03-07 17:42

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='body',
            field=wagtail.fields.StreamField([('paragraph', 0), ('image', 1), ('code', 4), ('embed', 5), ('heading', 6), ('quote', 7), ('table', 8)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 2: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('bash', 'Bash/Shell'), ('css', 'CSS'), ('dart', 'Dart'), ('diff', 'diff'), ('html', 'HTML'), ('java', 'Java'), ('kotlin', 'Kotlin'), ('javascript', 'Javascript'), ('json', 'JSON'), ('python', 'Python'), ('php', 'PHP'), ('scss', 'SCSS'), ('sql', 'SQL'), ('swift', 'Swift'), ('typescript', 'TypeScript'), ('xml', 'XML'), ('yaml', 'YAML')], 'help_text': 'Coding language', 'identifier': 'language', 'label': 'Language'}), 3: ('wagtail.blocks.TextBlock', (), {'identifier': 'code', 'label': 'Code'}), 4: ('wagtail.blocks.StructBlock', [[('language', 2), ('code', 3)]], {}), 5: ('wagtail.embeds.blocks.EmbedBlock', (), {}), 6: ('wagtail.blocks.CharBlock', (), {'form_classname': 'full title'}), 7: ('wagtail.blocks.BlockQuoteBlock', (), {}), 8: ('wagtail.contrib.table_block.blocks.TableBlock', (), {})}),
        ),
        migrations.CreateModel(
            name='BlogPageGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('caption', models.CharField(blank=True, max_length=250)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='blog.blogpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
